[font]
size = 14.0

[window]
dynamic_title = false
startup_mode = "Fullscreen"
title = "92b2708d-7a7a-41cf-ad6b-69503c4f95bd"

[window.dimensions]
columns = 110
lines = 28

[window.position]
x = 0
y = 0
